// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using homeworkFromTg.Date;

#nullable disable

namespace homeworkFromTg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427145044_AddEntityAlias")]
    partial class AddEntityAlias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("homeworkFromTg.Aliases.TitleAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleAlias");
                });

            modelBuilder.Entity("homeworkFromTg.Base.BasePersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NativeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Base.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("boolean");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Base.CommentLike", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("boolean");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Base.EntityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Base.SelectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SelectionId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Base.UserListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.ProfileUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProfileUser");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Selection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Selection");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.BasePersonEntity");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeigthCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BloodType = "O",
                            Description = "A skilled swordsman with a mysterious past.",
                            FavoritesCount = 1542,
                            Gender = "Male",
                            ImagePath = "/images/alex_storm.png",
                            Name = "Alex Storm",
                            NativeName = "アレックス・ストーム",
                            Age = 24,
                            Birthday = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 178.5m,
                            WeightKg = 72.0m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            BloodType = "A",
                            Description = "A talented healer who loves nature.",
                            FavoritesCount = 2301,
                            Gender = "Female",
                            ImagePath = "/images/luna_spark.png",
                            Name = "Luna Spark",
                            NativeName = "ルナ・スパーク",
                            Age = 19,
                            Birthday = new DateTime(2004, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 165.0m,
                            WeightKg = 54.2m
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.BasePersonEntity");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deathday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hometown")
                        .HasColumnType("text");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BloodType = "B",
                            Description = "Award-winning animation director.",
                            FavoritesCount = 450,
                            Gender = "Male",
                            ImagePath = "/images/kenjiro_tanaka.png",
                            Name = "Kenjiro Tanaka",
                            NativeName = "田中 健二郎",
                            Birthday = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hometown = "Tokyo, Japan"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BloodType = "AB",
                            Description = "Best-selling light novel author.",
                            FavoritesCount = 890,
                            Gender = "Female",
                            ImagePath = "/images/yumi_sato.png",
                            Name = "Yumi Sato",
                            NativeName = "佐藤 由美",
                            Birthday = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hometown = "Kyoto, Japan"
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Comments.CharacterComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.EpisodeComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.SelectionComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.HasIndex("SelectionId");

                    b.ToTable("SelectionComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.StaffComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.TitleComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.UserComment", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.Comment");

                    b.Property<Guid>("ProfileUserId")
                        .HasColumnType("uuid");

                    b.HasIndex("ProfileUserId");

                    b.ToTable("UserComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.CharacterCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("CharacterCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterCommentId");

                    b.ToTable("CharacterCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.EpisodeCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("EpisodeCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("EpisodeCommentId");

                    b.ToTable("EpisodeCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.SelectionCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("SelectionCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("SelectionCommentId");

                    b.ToTable("SelectionCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.StaffCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("StaffCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("StaffCommentId");

                    b.ToTable("StaffCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.TitleCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("TitleCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleCommentId");

                    b.ToTable("TitleCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.UserCommentLike", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.CommentLike");

                    b.Property<Guid>("UserCommentId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserCommentId");

                    b.ToTable("UserCommentLike");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.CharacterResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.EntityResource");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterResources");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.StaffResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.EntityResource");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffResource");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.TitleResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.EntityResource");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleResource");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.TitleSelectionItem", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.SelectionItem");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleSelectionItems");
                });

            modelBuilder.Entity("homeworkFromTg.SelectionItems.CharacterSelectionItem", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.SelectionItem");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSelectionItems");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.CharacterListEntry", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.UserListEntry");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterListEntries");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.StaffListEntry", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.UserListEntry");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffListEntries");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.TitleListEntry", b =>
                {
                    b.HasBaseType("homeworkFromTg.Base.UserListEntry");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleListEntries");
                });

            modelBuilder.Entity("homeworkFromTg.Aliases.TitleAlias", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("homeworkFromTg.Base.Comment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("homeworkFromTg.Base.CommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("homeworkFromTg.Base.SelectionItem", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Selection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("homeworkFromTg.Base.UserListEntry", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "SeoMetadata", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("SeoMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "SeoMetadata", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("SeoMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("homeworkFromTg.Comments.CharacterComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.EpisodeComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.SelectionComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Selection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.StaffComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.TitleComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.UserComment", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.ProfileUser", "ProfileUser")
                        .WithMany()
                        .HasForeignKey("ProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileUser");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.CharacterCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.CharacterComment", "CharacterComment")
                        .WithMany()
                        .HasForeignKey("CharacterCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.EpisodeCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.EpisodeComment", "EpisodeComment")
                        .WithMany()
                        .HasForeignKey("EpisodeCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EpisodeComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.SelectionCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.SelectionComment", "SelectionComment")
                        .WithMany()
                        .HasForeignKey("SelectionCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectionComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.StaffCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.StaffComment", "StaffComment")
                        .WithMany()
                        .HasForeignKey("StaffCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.TitleCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.TitleComment", "TitleComment")
                        .WithMany()
                        .HasForeignKey("TitleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleComment");
                });

            modelBuilder.Entity("homeworkFromTg.Comments.UserCommentLike", b =>
                {
                    b.HasOne("homeworkFromTg.Comments.UserComment", "UserComment")
                        .WithMany()
                        .HasForeignKey("UserCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserComment");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.CharacterResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.StaffResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("homeworkFromTg.Resources.TitleResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.TitleSelectionItem", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("homeworkFromTg.SelectionItems.CharacterSelectionItem", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.CharacterListEntry", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.StaffListEntry", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("homeworkFromTg.ListEntries.TitleListEntry", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
