// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using homeworkFromTg.Date;

#nullable disable

namespace homeworkFromTg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426160349_AddEntityResource")]
    partial class AddEntityResource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("homeworkFromTg.Entities.BasePersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NativeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.EntityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.BasePersonEntity");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeigthCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BloodType = "O",
                            Description = "A skilled swordsman with a mysterious past.",
                            FavoritesCount = 1542,
                            Gender = "Male",
                            ImagePath = "/images/alex_storm.png",
                            Name = "Alex Storm",
                            NativeName = "アレックス・ストーム",
                            Age = 24,
                            Birthday = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 178.5m,
                            WeightKg = 72.0m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            BloodType = "A",
                            Description = "A talented healer who loves nature.",
                            FavoritesCount = 2301,
                            Gender = "Female",
                            ImagePath = "/images/luna_spark.png",
                            Name = "Luna Spark",
                            NativeName = "ルナ・スパーク",
                            Age = 19,
                            Birthday = new DateTime(2004, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 165.0m,
                            WeightKg = 54.2m
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.BasePersonEntity");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deathday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hometown")
                        .HasColumnType("text");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BloodType = "B",
                            Description = "Award-winning animation director.",
                            FavoritesCount = 450,
                            Gender = "Male",
                            ImagePath = "/images/kenjiro_tanaka.png",
                            Name = "Kenjiro Tanaka",
                            NativeName = "田中 健二郎",
                            Birthday = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hometown = "Tokyo, Japan"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BloodType = "AB",
                            Description = "Best-selling light novel author.",
                            FavoritesCount = 890,
                            Gender = "Female",
                            ImagePath = "/images/yumi_sato.png",
                            Name = "Yumi Sato",
                            NativeName = "佐藤 由美",
                            Birthday = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hometown = "Kyoto, Japan"
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Entities.CharacterResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.EntityResource");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterResources");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.StaffResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.EntityResource");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffResource");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.TitleResource", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.EntityResource");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasIndex("TitleId");

                    b.ToTable("TitleResource");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "SeoMetadata", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("SeoMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "SeoMetadata", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("SeoMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.CharacterResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.StaffResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("homeworkFromTg.Entities.TitleResource", b =>
                {
                    b.HasOne("homeworkFromTg.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
