// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using homeworkFromTg.Date;

#nullable disable

namespace homeworkFromTg.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426123153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("homeworkFromTg.Entities.BasePersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FavoritesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NativeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.BasePersonEntity");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HeigthCm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BloodType = "O",
                            Description = "A skilled swordsman with a mysterious past.",
                            FavoritesCount = 1542,
                            Gender = "Male",
                            ImagePath = "/images/alex_storm.png",
                            Name = "Alex Storm",
                            NativeName = "アレックス・ストーム",
                            Age = 24,
                            Birthday = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 178.5m,
                            WeightKg = 72.0m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            BloodType = "A",
                            Description = "A talented healer who loves nature.",
                            FavoritesCount = 2301,
                            Gender = "Female",
                            ImagePath = "/images/luna_spark.png",
                            Name = "Luna Spark",
                            NativeName = "ルナ・スパーク",
                            Age = 19,
                            Birthday = new DateTime(2004, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 165.0m,
                            WeightKg = 54.2m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            BloodType = "A",
                            Description = "Brave warrior",
                            FavoritesCount = 120,
                            Gender = "Male",
                            ImagePath = "/img/leo.png",
                            Name = "Leo",
                            NativeName = "レオ",
                            Age = 25,
                            Birthday = new DateTime(2000, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 180m,
                            WeightKg = 75m
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            BloodType = "B",
                            Description = "Swift archer",
                            FavoritesCount = 89,
                            Gender = "Female",
                            ImagePath = "/img/mia.png",
                            Name = "Mia",
                            NativeName = "ミア",
                            Age = 19,
                            Birthday = new DateTime(2006, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 165m,
                            WeightKg = 52m
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            BloodType = "O",
                            Description = "Dark mage",
                            FavoritesCount = 310,
                            Gender = "Male",
                            ImagePath = "/img/kai.png",
                            Name = "Kai",
                            NativeName = "カイ",
                            Age = 32,
                            Birthday = new DateTime(1993, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 188m,
                            WeightKg = 84m
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            BloodType = "AB",
                            Description = "Healer",
                            FavoritesCount = 450,
                            Gender = "Female",
                            ImagePath = "/img/sora.png",
                            Name = "Sora",
                            NativeName = "ソラ",
                            Age = 21,
                            Birthday = new DateTime(2004, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeigthCm = 160m,
                            WeightKg = 48m
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.HasBaseType("homeworkFromTg.Entities.BasePersonEntity");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deathday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hometown")
                        .HasColumnType("text");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BloodType = "B",
                            Description = "Award-winning animation director.",
                            FavoritesCount = 450,
                            Gender = "Male",
                            ImagePath = "/images/kenjiro_tanaka.png",
                            Name = "Kenjiro Tanaka",
                            NativeName = "田中 健二郎",
                            Birthday = new DateTime(1975, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Tokyo, Japan"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            BloodType = "AB",
                            Description = "Best-selling light novel author.",
                            FavoritesCount = 890,
                            Gender = "Female",
                            ImagePath = "/images/yumi_sato.png",
                            Name = "Yumi Sato",
                            NativeName = "佐藤 由美",
                            Birthday = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Kyoto, Japan"
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            BloodType = "A",
                            Description = "Lead animator",
                            FavoritesCount = 75,
                            Gender = "Male",
                            ImagePath = "/img/tanaka.png",
                            Name = "Hiroshi Tanaka",
                            NativeName = "田中博",
                            Birthday = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2022, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Osaka"
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            BloodType = "B",
                            Description = "Character designer",
                            FavoritesCount = 130,
                            Gender = "Female",
                            ImagePath = "/img/sato.png",
                            Name = "Yuki Sato",
                            NativeName = "佐藤雪",
                            Birthday = new DateTime(1992, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Tokyo"
                        },
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000003"),
                            BloodType = "O",
                            Description = "Director",
                            FavoritesCount = 500,
                            Gender = "Male",
                            ImagePath = "/img/watanabe.png",
                            Name = "Ken Watanabe",
                            NativeName = "渡辺健",
                            Birthday = new DateTime(1970, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Kyoto"
                        },
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000004"),
                            BloodType = "AB",
                            Description = "Sound director",
                            FavoritesCount = 90,
                            Gender = "Female",
                            ImagePath = "/img/yamamoto.png",
                            Name = "Aiko Yamamoto",
                            NativeName = "山本愛子",
                            Birthday = new DateTime(1985, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deathday = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            hometown = "Nagoya"
                        });
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Character", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "seoMetadata", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Character");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("seoMetadata")
                        .IsRequired();
                });

            modelBuilder.Entity("homeworkFromTg.Entities.Staff", b =>
                {
                    b.OwnsOne("homeworkFromTg.Entities.SeoMetadata", "seoMetadata", b1 =>
                        {
                            b1.Property<Guid>("StaffId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("StaffId");

                            b1.ToTable("Staff");

                            b1.WithOwner()
                                .HasForeignKey("StaffId");
                        });

                    b.Navigation("seoMetadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
